checkbox-provider-arm/units/device/test-plan.pxu
Since I missed the test plan part of dtb in the previous commit for fix the typo.
=> Fix: test plan for dtb

checkbox-provider-ce-oem/bin/cold_reboot_by_pdu.sh, checkbox-provider-ce-oem/bin/reboot_check_test.sh, checkbox-provider-ce-oem/units/power-management/jobs.pxu, checkbox-provider-ce-oem/units/power-management/test-plan.pxu, checkbox-provider-ce-oem/units/stress/boot.pxu, checkbox-provider-ce-oem/units/stress/test-plan.pxu
add cold reboot tests by network PDU for those system which not able to wakeup by rtc
ceqa@ceqa:~$ checkbox.checkbox-cli list-bootstrapped com.canonical.qa.ceoem::power-automated-by-pdu
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/ceqa/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Using sideloaded provider: checkbox-provider-ce-oem, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-ce-oem/checkbox-provider-ce-oem
com.canonical.qa.ceoem::power-management/cold-reboot-by-pdu
com.canonical.qa.ceoem::power-management/post-cold-reboot-by-pdu
https://pastebin.canonical.com/p/YRgwFNzVvt/
=> Add: support cold reboot tests by pdu

README.md
Adding information about the used config for test jobs in the readme file. To let the user know what kinds of config need to be set in checkbox config before using the jobs in provider-ce-oem.
=> Add: informations about used config in readme

checkbox-provider-ce-oem/units/rtc/jobs.pxu
rtc alarm should be written into /sys/class/rtc/rtcX/wakealarm instead of /sys/class/rtc/rtcX/device/power/wakeup.
=> Fix: rtc wakealarm checking to right attribute

checkbox-provider-ce-oem/units/test-plan-ce-oem-full-classic.pxu, checkbox-provider-ce-oem/units/test-plan-ce-oem-full-core.pxu, checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu
commit 904f8312d0d31cab1e0075c76c9cd9aef24b3819 (HEAD -> 230426_add-generic-full-plan, origin/230426_add-generic-full-plan)
Author: stanley31huang <stanley.huang@canonical.com>
Date:   Wed Apr 26 13:53:54 2023 +0800
Add: add a generic iot test plans
Adding a generic IoT test plans, it's a full testing set include tests
in certification test plan and ce-oem-generic test plan
commit 0d285ca70a1ef47cf0db2922a674d71cd078295d
Author: stanley31huang <stanley.huang@canonical.com>
Date:   Wed Apr 26 13:48:34 2023 +0800
Fix: remove ce-oem-power-automated-by-pdu
Remove the ce-oem-power-automated-by-pdu from the ce-oem-automated
The ce-oem-power-automated-by-pud will always be executed even the user
not intend to reboot the DUT by PDU. And the checkbox session will stuck
after send out a snmpset …
=> 230426 add generic full plan

checkbox-provider-ce-oem/bin/mtd.sh
Before doing the read and write testing of specific MTD partition, we need to know the MTD is read-only or writable, therefore, a new variable called is_mtd_writable to help us to identify it.
The definition of **MTD_WRITEABLE** flag can reference the [mtd-utils](https://github.com/vamanea/mtd-utils/blob/bb0130e662ce6160433241e93f3fd5167a25a681/include/mtd/mtd-abi.h#L102) source code. Once the specific partition of MTD contains this bit value, it means the partition is writable.
As for the **MTD_BIT_WRITEABLE** flag, it only means the MTD can be manipulated by single bit.
Please reference [[MTD] Introduce MTD_BIT_WRITEABLE](http://www.infradead.org/pipermail/linux-mtd-cvs/2006-May/005463.html) and [mtd-utils](https://github.com/vamanea/mtd-utils/blob/bb0130e662ce6160433241e93f3fd5167a25a68 …
=> Improve the MTD script

checkbox-provider-ce-oem/bin/af_alg_test.py, checkbox-provider-ce-oem/units/crypto/caam.pxu, checkbox-provider-ce-oem/units/crypto/category.pxu, checkbox-provider-ce-oem/units/crypto/crypto_generic.pxu, checkbox-provider-ce-oem/units/crypto/manifest.pxu, checkbox-provider-ce-oem/units/crypto/test-plan-caam.pxu, checkbox-provider-ce-oem/units/crypto/test-plan-crypto.pxu, checkbox-provider-ce-oem/units/crypto/test-plan.pxu, checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu
Add: CAAM related test
Porting CAAM-related test jobs from project Shiner.
And made some modifications for making I/O log more useful.
sideload result without manifest:
https://pastebin.canonical.com/p/6SFGZR65Hm/
content of resource job "cryptoinfo":
https://pastebin.canonical.com/p/GvrpzgcpV9/
Add: generic crypto test
Change rng and cryptoinfo as a generic crypto test.
Add a job to use cryptsetup to test the cryptographic performance of the system.
sideload result:
https://pastebin.canonical.com/p/ywXyhgxZFH/
https://pastebin.canonical.com/p/f5dY8w6YMX/
=> Add: CAAM related test

checkbox-provider-ce-oem/units/eeprom/test-plan.pxu
The name of test plan `after-suspend-eeprom-automated` is wrong, it should be `after-suspend-ce-oem-eeprom-automated`
=> Fix: wrong name of after-suspend-eeprom-automated

checkbox-provider-ce-oem/bin/digital_io_loopback_serial_test.py, checkbox-provider-ce-oem/bin/digital_io_loopback_test.py, checkbox-provider-ce-oem/units/digital-io/category.pxu, checkbox-provider-ce-oem/units/digital-io/jobs.pxu, checkbox-provider-ce-oem/units/digital-io/manifest.pxu, checkbox-provider-ce-oem/units/digital-io/test-plan.pxu
Adding the loopback tests for digital IO interface.
In common practice, the digital IO will be connected to the GPIO port. But there might be some special case that the digital IO interfaces are connected to a USB to GPIO controller, so you have to control the pin by serial console.
So I have implemented two type of digital IO tests for those ports control by GPIO and serial console.
- control by serial console
https://certification.canonical.com/hardware/202304-31538/submission/319323/
- control by GPIO
https://certification.canonical.com/hardware/202211-30871/submission/318757/
=> Add: add digital-io tests

checkbox-provider-ce-oem/units/digital-io/jobs.pxu, checkbox-provider-ce-oem/units/digital-io/test-plan.pxu
- corrected digital-io tests in post-suspend stage
- import manifest job
side load test results:
WARNING:checkbox-ng.launcher.stages:Using side-loaded providers disabled the certification report
☑ : Hardware Manifest
☑ : To test loopback between DO1 and DI1
☑ : To test loopback between DO2 and DI2
☑ : To test loopback between DO3 and DI3
☑ : To test loopback between DO4 and DI4
☑ : Create resource info for supported sleep states
☑ : Creates resource info for RTC
☑ : Automated test of suspend function
☑ : To test loopback between DO1 and DI1 after suspend (S3)
☑ : To test loopback between DO2 and DI2 after suspend (S3)
☑ : To test loopback between DO3 and DI3 after suspend (S3)
☑ : To test loopback between DO4 and DI4 after suspend (S3)
=> Fix: updated digital-io tests

checkbox-provider-ce-oem/bin/cpufreq_governors.py, checkbox-provider-ce-oem/units/cpu/jobs.pxu, checkbox-provider-ce-oem/units/cpu/test-plan.pxu
Add a resource job to check system supported governors, and test jobs for all 6 governors. These tests are only applicable to the platform using acpi_cpufreq related drivers. Newer Intel CPU using intel_pstate driver is NOT applicable.
Sideload result:
https://pastebin.canonical.com/p/FVZSGKVdwb/
=> Add: cpufreq governors test for 6 governors

checkbox-provider-ce-oem/units/crypto/caam.pxu, checkbox-provider-ce-oem/units/installation-time/jobs.pxu
Modify: modify hwrng and caam algo check to require manifest
Add: requires for installation related jobs
Make those jobs not run in Ubuntu classic and run only in Ubuntu Core
CAAM related jobs side load results with manifest false:
https://pastebin.canonical.com/p/mF2pJ3MXN6/
CAAM related jobs side load result without manifest:
https://pastebin.canonical.com/p/tn9VJS2Y7w/
Installation time related jobs side load result in Ubuntu Classic:
https://pastebin.canonical.com/p/7bvr3Xpnty/
=> Modify CAAM and installation time related jobs.

checkbox-provider-ce-oem/units/ptp/jobs.pxu
Move the manifest to the test job.
To prevent manifest from being executed at bootstrap stage.
=> Fix: manifest shouldn't place in resource job

.github/workflows/tox.yaml, checkbox-provider-ce-oem/tox.ini
Each tox test environment won't be reseted, therefore removing all providers before test is needed. After checking with checkbox repo, checkbox-ng has to use different install method to install.
=> Fix tox test environment error

checkbox-provider-ce-oem/bin/cpufreq_governors.py, checkbox-provider-ce-oem/units/cpu/jobs.pxu, checkbox-provider-ce-oem/units/cpu/test-plan.pxu
Task: https://warthogs.atlassian.net/browse/CQT-2906
The original script didn't handle the machine that doesn't enable the cpufreq feature well and didn't consider the machine with multiple policies. Therefore, this pull request refactors the script to policy-based tests.
* The `cpufreq_policy_list` resource job lists the CPU policies in the system and their corresponding scaling drivers.
* The `ce-oem-cpu/cpufreq_driver_detect` is to detect if the scaling drivers exist. It can be run on both ARM and Intel platforms.
* The `ce-oem-cpu/cpufreq-governor-.*-policy.*` jobs will only be generated when the scaling driver is not `intel_pstate`. And they also depend on `ce-oem-cpu/cpufreq_driver_detect`, which means if the scaling driver doesn't exist (fail), these jobs will be skipped.
* Class …
=> Refactor cpufreq governor test

checkbox-provider-ce-oem/units/ptp/jobs.pxu
lp:2030942, workaround for the current version of ptp4l, and we will try to build the latest version in checkbox-ce-oem in the future.
https://bugs.launchpad.net/shiner/+bug/2030942
Sideload result with x8high-pdk. PDK has two different ETH PHY, and both works fine.
https://certification.canonical.com/hardware/202304-31534/submission/327076/test-results/pass/
The result on Ti AM62:
root@am62xx-evm:~# ./ptp4l -i eth1 -m -s --network_transport=L2 --tx_timestamp_timeout=5
ptp4l[7863.164]: selected /dev/ptp0 as PTP clock
ptp4l[7863.225]: port 1: INITIALIZING to LISTENING on INIT_COMPLETE
ptp4l[7863.226]: port 0: INITIALIZING to LISTENING on INIT_COMPLETE
ptp4l[7863.700]: port 1: new foreign master a44cc8.fffe.2b5c7d-1
ptp4l[7865.700]: selected best master clock a44cc8.fffe.2b5c7d …
=> Change: PTP command

checkbox-provider-ce-oem/units/ptp/jobs.pxu, checkbox-provider-ce-oem/units/ptp/test-plan.pxu, checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu
Jira task: https://warthogs.atlassian.net/browse/CQT-3259
* Change: hardware PTP support keywords
For PTP capabilities, ethtool v5.4 (on Ubuntu 20.04) shows
`hardware-transmit     (SOF_TIMESTAMPING_TX_HARDWARE)`
But ethtool v5.16 (on Ubuntu 22.04) only shows
`hardware-transmit`
The test case was using `SOF_TIMESTAMPING_TX_HARDWARE` as keywords,
This commit changes it to use `hardware-transmit` for adapting new
version of ethtool.
* Remove: nested ptp-manual test plans
The current manual test job steps are duplicated with the auto test job.
Currently we only need to run the auto test job.
The manual test steps here is used as a reference.
If there are new jobs in th future, the ptp-manual test plan can be
nested back.
* Running on a ubuntu 20.04 laptop …
=> Update ptp tests

checkbox-provider-ce-oem/bin/multiple-otg.sh
Since we observed a few patterns on different ARM-based platforms. So add additional patterns to map UDC and USB node.
Test result 1:
https://pastebin.canonical.com/p/jTz6K6xtmZ/
Test result 2:
ubuntu@:~$ ./multiple-otg.sh -c "j1:11200000 j2:112a1000"
USB_port: j1
USB_Node: 11200000
Mode: otg
UDC: 11201000.usb
USB_port: j2
USB_Node: 112a1000
Mode: otg
UDC: 112a1000.usb
Test result 3:
ubuntu:~$ ./multiple-otg.sh -c "j1:38200000 j2:38100000"
USB_port: j1
USB_Node: 38200000
Mode: otg
UDC: 38200000.usb
USB_port: j2
USB_Node: 38100000
Mode: otg
UDC: 38100000.usb
=> Change: additional patterns to map UDC and USB node

checkbox-provider-ce-oem/tox.ini
include the python3-systemd package in tox.ini
I have implemented a python scripts with systemd module, but the python3-systemd is not built-in in the test environment.
the tox.ini file has been validated on my personal repo
https://github.com/stanley31huang/checkbox-provider-ce-oem/actions/runs/6233031599
=> Fix: include python3-systemd in tox.ini

checkbox-provider-ce-oem/bin/mtd.sh
The original script uses `grep -c` to count the numbers of mtds. The return code will be 1 `grep` failed (mtd not supported). With `set -e`, the script will break instantly which makes the `countMtd()` function not able to print anything and get the wrong result.
Fix the `grep -c` back to `wc -l` that was used in Shiner project. It will return 0 even if mtd is not found, which can make the test script and job work properly.
Test results on device not supported mtd:
```
iotuc@ubuntu:~$ sudo ./mtd.sh count 0
The number of MTD is correct!
```
Reference for shellcheck 2126
https://www.shellcheck.net/wiki/SC2126
=> Fix: errors when mtd count is 0

checkbox-provider-ce-oem/units/optee/README.md, checkbox-provider-ce-oem/units/optee/jobs.pxu
Add: support outsourcing optee-test
Add: config var explanation in README.md
sideload result for TI-EVK(out sourcing optee-test): 
https://certification.canonical.com/hardware/202308-31996/submission/331513/
sideload result for high-pdk(build-in optee-test in gadget):
https://certification.canonical.com/hardware/202304-31534/submission/331171/
=> Modify optee test run out of gadget

checkbox-provider-ce-oem/units/otg/jobs.pxu
Add a `if condition` to handle when the OTG config variable is not set. We expect the resource job not to fail even if the OTG feature is not supported.
Adding a `:` after the sentence because Checkbox will check the format for the resource job which usually needs to be `key:value`. If `:` is not added, there will be a warning
```sh
invalid RFC822 data: Unexpected non-empty line: 'OTG config variable not found' (line 1)
```
Sideload result:
```
iotuc@ubuntu:~$ checkbox-shiner.checkbox-cli run .*::otg_ports
Using sideloaded provider: checkbox-provider-ce-oem, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-ce-oem
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:00:01 ]=============== …
```
=> Revamp otg_ports resource job should not fail

checkbox-provider-ce-oem/units/installation-time/jobs.pxu
ce-oem-info jobs are aimed at collecting the system bootup information from snapd and cloud-init to help developers analyze bugs. Therefore, these jobs are more suitable to be attachment jobs and should not fail even if some information can not be found. For example, some systems may not have cloud-init. In these systems, the job cannot gather the information from cloud-init, but this should not be a failure.
Sideload result:
https://pastebin.canonical.com/p/rvPq7pPD7r/
=> Make ce-oem-info jobs be attachment jobs

checkbox-provider-ce-oem/units/crypto/accelerator.pxu
Some of the project devices' caam_hwrng have buffer, so previously the dd size was increased to 10M to exceed the buffer size to make the interrupt increased. But it will make the device without buffer take a very long time (over 30 mins) to do the dd command.
Therefore, this commit separated the size to 512K and looped it 20 times. On the device without buffer it could do 512K and detect the increased interrupt to get the pass result, which is much faster. On the device with buttfer it could also exceed the buffer by dd 20 times and detect the increased interrupt to get the pass result.
Sideload result without manifest
https://pastebin.canonical.com/p/8QT5RxbQN9/
The first device has buffer, the second device doesn't have buffer.
=> Revamp caam_hwrng_test by looping w/ smaller size

checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu
Previously the caam test plan was revamped to accelerator test plan, but forgot to update the name nested in ce-oem-automated. Fix the name in this commit.
=> Fix the nested crypto test plan name

checkbox-provider-ce-oem/bin/socketcan_busoff_test.py, checkbox-provider-ce-oem/bin/socketcan_socket.py, checkbox-provider-ce-oem/bin/socketcan_test.py, checkbox-provider-ce-oem/units/socketcan/jobs.pxu, checkbox-provider-ce-oem/units/socketcan/manifest.pxu, checkbox-provider-ce-oem/units/socketcan/test-plan.pxu
add new socketcan stress test (100000 loop echo test)
please refer the test results in Jira CQT-3562 issue
https://warthogs.atlassian.net/jira/software/projects/CQT/boards/418?selectedIssue=CQT-3562
Side-loading the checkbox and ran the socketcan-full test plan, please have the test results from C3:
- https://certification.canonical.com/hardware/202304-31451/submission/344073/
- https://certification.canonical.com/hardware/202304-31451/submission/344326/test-results/
following bus-off test failed as expected, I did not short the CAN_L and CAN_H in purpose.
- [after-suspend-ce-oem-socketcan/bus_off_recovery_can0](https://certification.canonical.com/hardware/202304-31451/submission/344073/test/204991/result/37757702/)
- [after-suspend-ce-oem-socketcan/bus_off_recovery_can1](https://certifica …
=> Add: new socketcan stress test

checkbox-provider-ce-oem/bin/graphics_test.sh, checkbox-provider-ce-oem/units/mir/category.pxu, checkbox-provider-ce-oem/units/mir/jobs.pxu, checkbox-provider-ce-oem/units/mir/manifest.pxu, checkbox-provider-ce-oem/units/mir/test-plan.pxu
This PR introduced tests for `ubuntu-frame` and `glmark2-es2-wayland` benchmark.
For ubuntu-frame, we checked whether it is already launching in the background
* If yes, we dump the journal log relevant to ubuntu-frame
* If not, we try to launch it for 20 seconds to see if there's any launching error.
For glmark2-es2-wayland benchmark, we run it by `graphics-test-tools`
* Try to see whether we can run the benchmark successfully and get the glmark2 score.
* Check whether the `GL_VENDOR` and `GL_RENDERER` is correct.
* To make sure the benchmark is running on the GPU, not by CPU software rendering (which the renderer starts with `llvm`)
* `GL_VENDOR` and `GL_RENDERER` need to be specified in the config variables.
Also added an ubuntu-frame manifest.
Sideload test results:
* On Shiner MB …
=> Add ubuntu-frame and glmark2 tests

checkbox-provider-ce-oem/bin/thermal_sensor_test.py, checkbox-provider-ce-oem/tests/test_thermal_sensor_test.py, checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu, checkbox-provider-ce-oem/units/thermal-sensor/category.pxu, checkbox-provider-ce-oem/units/thermal-sensor/jobs.pxu, checkbox-provider-ce-oem/units/thermal-sensor/test-plan.pxu
refactor the thermal tests
https://certification.canonical.com/hardware/202309-32029/submission/349191/
```
u@u-APC2200:~$ checkbox-ce-oem.checkbox-cli list-bootstrapped com.canonical.qa.ceoem::ce-oem-automated | grep "thermal\|sensor"
$PROVIDERPATH is defined, so following provider sources are ignored ['/snap/checkbox-ce-oem/110/providers/checkbox-provider-ce-oem', '/home/u/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Using sideloaded provider: checkbox-provider-ce-oem, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-ce-oem
com.canonical.qa.ceoem::ce-oem-thermal/temperature_thermal_zone0_acpitz
com.canonical.qa.ceoem::ce-oem-thermal/temperature_thermal_zone1_x86_pkg_temp
u@u-APC2200:~$ checkbox-ce-oem.checkbox-cli list-bootstrapped …
```
=> Fix: refactor the thermal tests
